stages:
  - test
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    # semantic-release currently only works on master
    if: branch = master

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install: pip install -r requirements/dev.txt
script: tox

jobs:
  include:
    - stage: deploy
      # use just ONE of the tested versions for deploy
      # and pick a version that has no issues
      python: 3.6
      script:
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - pip install --upgrade -r requirements/publish.txt
        - semantic-release publish
        
